python main.py --dataset shanghaitechpa \
--model MCCCN \
--train-files /data/CrowdCount/train.txt \
--val-files /data/CrowdCount/val.txt \
--gpu-devices 0 \
--lr 1e-6 \
--optim sgd \
--loss mseloss \
--checkpoints ./checkpoints/demo \
--summary-writer ./runs/demo \
--train-batch 1 